### ISSUE TITLE
Daily Notification- help

### ISSUE THREAD

**Issue by XxGoliathusxX** [alberto234/schedule-alarm-manager#3]
My goal is to show a notification daily on a user-chosen time. I tried Services and AlarmManager. Both failed because the service goes to sleep after a while and the AlarmManager has a bug in KitKat and I dont know how to handle it. Many tutorials are deprecated or simply wrong. So at the end I landed here. 
When the device screen is off, will it show an alarm nevertheless?
When the device restarts, will it show an alarm nevertheless?

Can you help me?

**Comment by alberto234** [comment]
The short answer to your questions is yes and yes. However, this depends on the app that is integrating to the library.

If I understand correctly based on your needs this library may be offering much more than what you need, since all you need is an alarm that happens daily. Without digging much into code, this is what I suggest.

**To issue the alarm after the device restarts**, your app will have to register for the BOOT_COMPLETED intent. The receiver for this intent will re-register with the AlarmManager for the next time that the alarm should trigger. Here are some code snippets from my manifest file

```
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <receiver android:name=".receivers.WurrdGenericBroadcastReceiver">
        <intent-filter>
            <action android:name="android.intent.action.BOOT_COMPLETED"/>
        </intent-filter>
        <intent-filter>
            <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
        </intent-filter>
    </receiver>
```

The WurrdGenericBroadcastReceiver is my receiver that registers the alarm again. Oh, and MY_PACKAGE_REPLACED is issued by the system after your app has been updated. If not your app will not run automatically after an update.

**To deal with the device off**, your receiver needs to be a WakefulBroadcastReceiver which acquires the partial wake lock that keeps the application awake in the background. In case you are performing a lengthy operation, you will also need to acquire a wake lock and release it when done. Read about wake locks. Below is a snippet of my receiver.

```
public class WurrdGenericBroadcastReceiver extends WakefulBroadcastReceiver {

@Override
public void onReceive(Context context, Intent intent) {
    String action = intent.getAction();

    // If we want to start the service with a wake lock acquired, call
    // startWakefulService(context, startServiceIntent);
    // You will need to call WurrdGenericBroadcastReceiver.completeWakefulIntent(intent) in
    // the service after work is complete
           ....
```

You also need the WAKE_LOCK permission in your manifest.

```
<uses-permission android:name="android.permission.WAKE_LOCK"/>
```

The above is to give you some direction on how to achieve your goals. I think this library is not what you are looking for but if you think so and need help integrating to the library let me know.

Thanks,

Eyong

**Comment by XxGoliathusxX** [comment]
Ok thanks for your advice!
